language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install

env:
  - NEO4J_VERSION="3.5.0"

jdk:
  - oraclejdk7  # needed for local Neo4j 2.0+

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-$NEO4J_VERSION/conf/neo4j-server.properties
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start

script:
  - cd test
  - python test_all.py
  - coverage run --source=brain2neo test_all.py

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - coveralls