language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install

env:
  - NEO4J_VERSION="3.5.0"

jdk:
  - oraclejdk7  # needed for local Neo4j 2.0+

services:
  - neo4j

script:
  - cd test
  - python test_all.py
  - coverage run --source=brain2neo test_all.py

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - coveralls